POST  http://localhost:3000/api/transactions
Content-Type: application/json

{
    "name": "expense",
    "type": "rent",
    "amount": 5000
}

###
GET  http://localhost:3000/api/transactions

###
GET  http://localhost:3000/api/labels